name: ci

on:
  push:
    branches:
      - earthly-main
      - gh_test_ci
  pull_request:
    branches:
      - earthly-main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GO_VERSION: ["1.13", "1.14", "1.15", "1.16"]
    env:
      GO_VERSION: ${{ matrix.GO_VERSION }}
    steps:
      -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          docker buildx bake
      -
        name: Test
        run: |
          docker buildx bake test
      -
        name: Linters
        run: |
          docker buildx bake lint validate-gomod validate-shfmt
      -
        name: Cross
        run: |
          docker buildx bake cross
